"""Import Batch 03 GLB sources into isolated Unreal content folders and validate them."""

from __future__ import annotations

import json
from pathlib import Path

import unreal


PROJECT = Path(unreal.SystemLibrary.get_project_directory())
ART = PROJECT / "Art" / "Weapons" / "ProductionBatch03"
MANIFEST = ART / "Metadata" / "SalvageGameplayBatch03.json"
DEST_ROOT = "/Game/Assets/Models/GameplayItems/SalvageBatch03"
REPORT = PROJECT / "Saved" / "Reports" / "SalvageGameplayBatch03Import.json"


def static_meshes_under(folder):
    result = []
    for path in unreal.EditorAssetLibrary.list_assets(folder, recursive=True, include_folder=False):
        asset = unreal.EditorAssetLibrary.load_asset(path)
        if isinstance(asset, unreal.StaticMesh):
            result.append(asset)
    return result


def import_entry(entry, category):
    source = ART / entry["export"]
    if not source.exists():
        raise RuntimeError(f"Missing Batch 03 source: {source}")
    destination = f"{DEST_ROOT}/{category}/{entry['id']}"
    unreal.EditorAssetLibrary.make_directory(destination)

    task = unreal.AssetImportTask()
    task.set_editor_property("filename", str(source))
    task.set_editor_property("destination_path", destination)
    task.set_editor_property("automated", True)
    task.set_editor_property("replace_existing", True)
    task.set_editor_property("replace_existing_settings", False)
    task.set_editor_property("save", False)
    unreal.AssetToolsHelpers.get_asset_tools().import_asset_tasks([task])

    meshes = static_meshes_under(destination)
    if not meshes:
        raise RuntimeError(f"No StaticMesh was imported for {entry['id']} into {destination}")

    records = []
    for mesh in meshes:
        try:
            settings = mesh.get_editor_property("nanite_settings")
            settings.set_editor_property("enabled", True)
            mesh.set_editor_property("nanite_settings", settings)
        except Exception as exc:
            unreal.log_warning(f"Nanite setup skipped for {mesh.get_name()}: {exc}")
        unreal.EditorAssetLibrary.save_loaded_asset(mesh)
        bounds = mesh.get_bounds()
        records.append({
            "asset": mesh.get_path_name(),
            "bounds_origin_cm": [bounds.origin.x, bounds.origin.y, bounds.origin.z],
            "bounds_extent_cm": [bounds.box_extent.x, bounds.box_extent.y, bounds.box_extent.z],
            "material_slots": len(mesh.static_materials),
        })
    return {
        "content_id": entry["id"],
        "category": category,
        "destination": destination,
        "source": str(source.relative_to(PROJECT)).replace("\\", "/"),
        "static_meshes": records,
        "imported_object_paths": list(task.get_editor_property("imported_object_paths")),
    }


def main():
    payload = json.loads(MANIFEST.read_text(encoding="utf-8"))
    # This directory is fully generated by this script. Clean it so removed or
    # renamed construction parts from earlier imports cannot survive as orphans.
    if unreal.EditorAssetLibrary.does_directory_exist(DEST_ROOT):
        unreal.EditorAssetLibrary.delete_directory(DEST_ROOT)
        leftovers = unreal.EditorAssetLibrary.list_assets(DEST_ROOT, recursive=True, include_folder=False)
        if leftovers:
            raise RuntimeError(f"Could not clean generated import assets under {DEST_ROOT}: {leftovers}")
    records = []
    for entry in payload["gear"]:
        records.append(import_entry(entry, "Gear"))
    for entry in payload["objects"]:
        records.append(import_entry(entry, "WorldObjects"))

    unreal.EditorAssetLibrary.save_directory(DEST_ROOT, only_if_is_dirty=False, recursive=True)
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    report = {
        "batch": "03",
        "destination": DEST_ROOT,
        "entries_imported": len(records),
        "static_meshes_imported": sum(len(record["static_meshes"]) for record in records),
        "entries": records,
    }
    REPORT.write_text(json.dumps(report, indent=2), encoding="utf-8")
    unreal.log(f"Batch 03 import complete: {len(records)} entries; report {REPORT}")


if __name__ == "__main__":
    main()
