#pragma once

#include "CoreMinimal.h"
#include "Templates/SubclassOf.h"
#include "UObject/UObjectGlobals.h"

/**
 * Shared convention for preferring an authored Widget Blueprint over its native C++ class.
 *
 * Screens live at /Game/UI/Widgets/WBP_<Screen> and are generated by
 * tools/build_menu_widget_blueprints.py. Resolution is by path rather than by hard reference so a
 * missing, renamed, or deleted Blueprint degrades to the native layout instead of leaving a screen
 * that cannot open.
 *
 * Resolve at point of use (subsystem Initialize, BeginPlay, layout construction) -- never from a
 * UObject constructor. Constructors run during CDO creation at module load, where loading an asset
 * is unsafe and would bake the result into the CDO.
 */
namespace GinnungagapMenuWidgets
{
	template <typename TWidget>
	TSubclassOf<TWidget> ResolveClass(const TCHAR* BlueprintClassPath)
	{
		if (UClass* Authored = LoadClass<TWidget>(nullptr, BlueprintClassPath))
		{
			return Authored;
		}
		return TWidget::StaticClass();
	}
}

// Blueprint class paths carry the _C suffix: that is the generated class, not the asset itself.
#define GINNUNGAGAP_MENU_WBP(Name) TEXT("/Game/UI/Widgets/WBP_" Name "." "WBP_" Name "_C")
