"""Placement audit of the corvette's dressing: what crosses a wall, what sits in what, and what
stands near a wall without touching it. Headless:

    UnrealEditor-Cmd.exe <project> -ExecutePythonScript=<abs>/tools/placement_audit.py -NullRHI

Writes docs/CorvettePlacement.md. Structure (walls, floors, ceilings, doors, rails, pipes,
ramps, lights, signs) is left out; everything else placed by the generator is checked against
the room rectangles and against each other.
"""
import os
import unreal

MAP = "/Game/Assets/Maps/ShipProduction/L_Corvette_ThrustStack"
DECK_PITCH = 430.0
ROOMS = {"Main": (0.0, 1500.0, 1000.0, 1800.0), "Second": (1500.0, 2400.0, 1000.0, 1800.0),
         "Service": (1400.0, 2400.0, 0.0, 600.0), "Corridor": (0.0, 2400.0, 600.0, 1000.0), "Trunk": (0.0, 1400.0, 0.0, 600.0)}
STRUCTURE = ("Wall", "Floor", "Ceiling", "Door", "Rail", "Pipe", "Ramp", "Light", "Practical", "Sign", "Fixture", "Lamp", "Beacon",
             "NavMesh", "Partition", "Plate", "Frame", "Hazard", "Smoke", "Exposure", "Sky", "Landing", "Grate", "Hull", "Deck", "Trim", "Lintel", "Hang", "Cable",
             "Fore", "Aft", "Port", "Stbd", "Pillar", "Ceiling", "Lane", "Head", "Foot", "Airlock", "Crawl", "Collapse", "Supply_")

unreal.EditorLoadingAndSavingUtils.load_map(MAP)
props = []
for a in unreal.EditorLevelLibrary.get_all_level_actors():
    label = a.get_actor_label()
    if not label.startswith("CVT_") or any(s in label for s in STRUCTURE):
        continue
    if not a.get_components_by_class(unreal.StaticMeshComponent) and not a.get_components_by_class(unreal.SkeletalMeshComponent):
        continue
    origin, extent = a.get_actor_bounds(True)
    if extent.x < 5 or extent.y < 5:
        continue
    props.append((label, a.get_class().get_name(), origin, extent))

lines = ["# Corvette placement audit", "", "Generated by `tools/placement_audit.py`; regenerate, do not edit.", ""]
wall_hits, overlaps, near = [], [], []
for label, cls, o, e in props:
    deck = int(o.z // DECK_PITCH) + 1
    z0 = (deck - 1) * DECK_PITCH
    x0, x1, y0, y1 = o.x - e.x, o.x + e.x, o.y - e.y, o.y + e.y
    # The room whose rectangle holds the centre.
    room = next((r for r, (rx0, rx1, ry0, ry1) in ROOMS.items() if rx0 <= o.x <= rx1 and ry0 <= o.y <= ry1), None)
    if room:
        # The rectangles are wall centre lines; the faces are a wall's half-thickness in.
        rx0, rx1, ry0, ry1 = (v + d for v, d in zip(ROOMS[room], (17.0, -17.0, 17.0, -17.0)))
        cross = max(rx0 - x0, x1 - rx1, ry0 - y0, y1 - ry1)
        if cross > 12.0:
            wall_hits.append(f"| {label} | {cls} | {deck} | {room} | ({o.x:.0f}, {o.y:.0f}) | {cross:.0f} |")
        gap = min(x0 - rx0, rx1 - x1, y0 - ry0, ry1 - y1)
        if 12.0 < gap < 90.0 and e.x + e.y < 260.0:
            near.append(f"| {label} | {cls} | {deck} | {room} | ({o.x:.0f}, {o.y:.0f}) | {gap:.0f} |")
for i in range(len(props)):
    la, ca, oa, ea = props[i]
    for j in range(i + 1, len(props)):
        lb, cb, ob, eb = props[j]
        if abs(oa.z - ob.z) > 400:
            continue
        ox = min(oa.x + ea.x, ob.x + eb.x) - max(oa.x - ea.x, ob.x - eb.x)
        oy = min(oa.y + ea.y, ob.y + eb.y) - max(oa.y - ea.y, ob.y - eb.y)
        oz = min(oa.z + ea.z, ob.z + eb.z) - max(oa.z - ea.z, ob.z - eb.z)
        if ox > 15 and oy > 15 and oz > 15:
            small = min(ea.x * ea.y, eb.x * eb.y) * 4.0
            share = (ox * oy) / max(small, 1.0)
            if share > 0.25:
                overlaps.append(f"| {la} | {lb} | {int(oa.z // DECK_PITCH) + 1} | ({oa.x:.0f}, {oa.y:.0f}) | {share * 100:.0f}% |")

lines += [f"## Through a wall ({len(wall_hits)})", "", "| Prop | Class | Deck | Room | Where | Over the wall (cm) |", "|---|---|---|---|---|---|"] + wall_hits + [""]
lines += [f"## In each other ({len(overlaps)})", "", "| Prop | Prop | Deck | Where | Footprint shared |", "|---|---|---|---|---|"] + overlaps + [""]
lines += [f"## Near a wall but not against it ({len(near)})", "", "| Prop | Class | Deck | Room | Where | Gap (cm) |", "|---|---|---|---|---|---|"] + near + [""]
lines += [f"Checked {len(props)} props."]
out = os.path.join(unreal.SystemLibrary.get_project_directory(), "docs", "CorvettePlacement.md")
with open(out, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print(f"PLACEMENT {len(props)} props, {len(wall_hits)} through walls, {len(overlaps)} overlapping, {len(near)} near walls -> {out}")
